sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-554.pdf --upload --lsstdoc LDM-554.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="ldm-554"
    # Add LSST the Docs credentials
    - secure: "USbzqq2HlxHNac8K0Vhdpm+wAPwTfS0esJzOT0B1wBQquS33afaVf9m8K76FeAceaNXpuWc51dvp9m2kxH1G203q25YvUrvGiNpXDiDDgIhqB8lxO+eAeK4pn7GyAwDwQxsFU5eqcN5RPI/O46D1ADf6HgZHU177bCl/8Pech2L19SKQvAnzzUEXDztu5+xjwvR8H9ytnF+jr9EnM3qmkuf58/wdZco7Nwmm/cvUDaanlRK4dOWoCIJvoZEPwzMq9J3JQBNVKbvf31hMxOR8lJTcgZCbmF18grrRRUf72qLV6Vh0gHj7Cpt+KNrrAI3fzbIHxxhzdrPHEc6CSuljEtohgrrhH70ED6O7ldOb5AsctFWUdT5vbc0aLJjGQwUgVtpsAoAPZxp7VP8y9d4aTD4+Xp6MFj6CdNSw/xtNgMDYQQyhde0XthBB16NX/sd7Pf+jezXzEb6rVZoXdX5ciHGziJJu70wf/p9VYwjiFlZAvy2/18LcGkcABNwMUVn9nQB0Dcky4iSicCrJSskUIlX5UObzvQs7OPPJwx5I+VDgOzcLPgtkykJgAX2ngaZsAtzp21RayusAB+gDZQXb57DSFntlAAM9z7yYE6FxbT7Yw/uyGblACg1Pk4MjbchY8niFT4XKdTDSUeD9kZKLRbqHwd848+i+0eoRHSBfPi0="
    - secure: "aFyhMdQUPbO/g1hdNBz0CyXMvFB6qX75ECgeMfL5kam0Z2VTiSuugnODHXajqleLeoGFnv1pvRSCI7GpTvEMcYiW4w+AXko4W5tpXvc8KNh6vT4FPf0clqq8NfWIDs4KPNmAXBoyeqiucvBUtsPZBDA4TUB72gu347lJ+XeHqy7LC5yfP7rq8G8qLoJLwVATT+nfBDlArkd/hht3dzjksWLLsIccHxb0B4FpSc8Av+KXCyx2rDmzLBNpfnYRxyW8MjcuXZXk1ogUylzspJxgX4ez+2Q2vFbdPivnpEYUjHZReQ/q+SJ5A3lXjFSZMiAxGLABpuoEToRWso8MTg9kdhcyXV2v8DM/ITtNzzBxH77PiBAtstga8TbHt8GewMrwOb8jdK0covcMQRhyPxFzBrwQk6Sh2842cWhtE3hNGhKDyloR5uVWHu9LzLnvJQ0Ks/3KbO4bMGSuRHpn5QEWj7Qwer9LRI+TefbV76SC4ArZqB77yyFukPGrHqrLWDZxEJaisruNXwsXxvQl08sszyUU10qtCSnF2nuU+5aitr5TxZjfU0CYs2Z63WMBM2nX6HRPxI+v9Aqw5RGWHTaqISoR3BOw63hsUmskUNWPd350qaepDDl7V7AxxB/F3+P8Ua+1fNhmB2uXHhPQgdUmPxkYch44L4KTjUL0uekS3vY="
